services:
    notes.collection_object_transformer:
        class: SymfonyNotes\ObjectTransformerBundle\Transformer\CollectionObjectTransformer
        lazy: true
        arguments:
            - '@notes.object_transformer'

    notes.object_transformer:
        class: SymfonyNotes\ObjectTransformerBundle\Transformer\ObjectTransformer
        calls:
            - [ addObjectTransformer, [ '@notes.collection_object_transformer' ] ]